"""Add table PromptRule

Revision ID: b33923296735
Revises: cb11b32ebfa0
Create Date: 2026-03-23 12:51:40.909193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33923296735'
down_revision: Union[str, Sequence[str], None] = 'cb11b32ebfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_rules_client_id'), 'prompt_rules', ['client_id'], unique=False)
    op.create_index(op.f('ix_prompt_rules_user_id'), 'prompt_rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_rules_user_id'), table_name='prompt_rules')
    op.drop_index(op.f('ix_prompt_rules_client_id'), table_name='prompt_rules')
    op.drop_table('prompt_rules')
    # ### end Alembic commands ###
