"""Initial migration

Revision ID: c23533804fa2
Revises: 
Create Date: 2026-03-23 12:01:51.969264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23533804fa2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_prompt_rules_client_id', table_name='prompt_rules')
    op.drop_index('ix_prompt_rules_user_email', table_name='prompt_rules')
    op.drop_index('ix_prompt_rules_user_id', table_name='prompt_rules')
    op.drop_table('prompt_rules')
    op.alter_column('prompt_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompt_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('prompt_rules',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_prompt_rules_user'),
    sa.PrimaryKeyConstraint('id', name='prompt_rules_pkey')
    )
    op.create_index('ix_prompt_rules_user_id', 'prompt_rules', ['user_id'], unique=False)
    op.create_index('ix_prompt_rules_user_email', 'prompt_rules', ['user_email'], unique=False)
    op.create_index('ix_prompt_rules_client_id', 'prompt_rules', ['client_id'], unique=False)
    # ### end Alembic commands ###
